# ============================================
# Stage 1: Dependencies Installation Stage
# ============================================

FROM oven/bun:1.3.13-alpine AS deps

WORKDIR /app

COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile

# =========================
# Stage 2 - builder
# =========================

FROM oven/bun:1.3.13-alpine AS builder

WORKDIR /app

ARG DATABASE_URL \
    POSTGRES_USER \
    POSTGRES_PASSWORD \
    POSTGRES_DB \
    BETTER_AUTH_SECRET \
    BETTER_AUTH_URL \
    SMTP_EMAIL \
    SMTP_PASSWORD \
    SMTP_HOST \
    SMTP_PORT \
    SMTP_FROM \
    GITHUB_CLIENT_ID \
    GITHUB_CLIENT_SECRET \
    REDIS_URL \
    GOOGLE_RECAPTCHA_SECRET_KEY \
    NEXT_PUBLIC_WEBSITE_URL \
    NEXT_PUBLIC_DISABLE_DEVTOOLS \
    NEXT_PUBLIC_SENTRY_DSN \
    NEXT_PUBLIC_GOOGLE_RECAPTCHA_PUBLIC_KEY

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    DATABASE_URL=$DATABASE_URL \
    POSTGRES_USER=$POSTGRES_USER \
    POSTGRES_PASSWORD=$POSTGRES_PASSWORD \
    POSTGRES_DB=$POSTGRES_DB \
    BETTER_AUTH_SECRET=$BETTER_AUTH_SECRET \
    BETTER_AUTH_URL=$BETTER_AUTH_URL \
    SMTP_EMAIL=$SMTP_EMAIL \
    SMTP_PASSWORD=$SMTP_PASSWORD \
    SMTP_HOST=$SMTP_HOST \
    SMTP_PORT=$SMTP_PORT \
    SMTP_FROM=$SMTP_FROM \
    GITHUB_CLIENT_ID=$GITHUB_CLIENT_ID \
    GITHUB_CLIENT_SECRET=$GITHUB_CLIENT_SECRET \
    REDIS_URL=$REDIS_URL \
    GOOGLE_RECAPTCHA_SECRET_KEY=$GOOGLE_RECAPTCHA_SECRET_KEY \
    NEXT_PUBLIC_WEBSITE_URL=$NEXT_PUBLIC_WEBSITE_URL \
    NEXT_PUBLIC_DISABLE_DEVTOOLS=$NEXT_PUBLIC_DISABLE_DEVTOOLS \
    NEXT_PUBLIC_SENTRY_DSN=$NEXT_PUBLIC_SENTRY_DSN \
    NEXT_PUBLIC_GOOGLE_RECAPTCHA_PUBLIC_KEY=$NEXT_PUBLIC_GOOGLE_RECAPTCHA_PUBLIC_KEY

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN bun run build

# =========================
# Stage 3 - runner
# =========================

FROM oven/bun:1.3.13-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    PORT=3000 \
    HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static

RUN rm -rf \
  /app/.next/cache \
  /app/node_modules/.cache \
  /tmp/* \
  /root/.bun \
  /root/.cache

EXPOSE 3000

CMD ["bun", "server.js"]
